# Generated by Django 2.0.6 on 2018-09-10 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorsanalytics', to='doctors.Doctor')),
            ],
        ),
        migrations.RemoveField(
            model_name='hitcount',
            name='url_hit',
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
        migrations.DeleteModel(
            name='UrlHit',
        ),
    ]
