# Generated by Django 2.0.6 on 2018-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workup',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/%Y/%m/%D/'),
        ),
    ]
