# Generated by Django 2.0.6 on 2018-07-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_auto_20180701_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.TextField(max_length=500)),
                ('test_description', models.TextField(max_length=500)),
                ('doctor', models.ManyToManyField(to='doctors.Doctor')),
            ],
        ),
    ]
