# Generated by Django 2.0.6 on 2018-10-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_pic',
            field=models.ImageField(blank=True, null=True, upload_to='tests/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
