# Generated by Django 2.0.6 on 2018-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='doctors.Doctor'),
        ),
    ]
