# Generated by Django 2.0.6 on 2018-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20181006_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_pic',
            field=models.ImageField(blank=True, null=True, upload_to='tests/%Y/%m/%D/'),
        ),
    ]
