# Generated by Django 2.0.6 on 2018-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/%Y/%m/%D/'),
        ),
    ]
