# Generated by Django 2.0.6 on 2018-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
