# Generated by Django 2.0.6 on 2018-09-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctors_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder'),
        ),
    ]
